name: Marketplace Module Builder

on:
  push:
    branches:
      - v*

jobs:
  build-and-upload:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]
        platform: [win-x64, win-x86, win-arm64]

    env:
      Solution_Name: Luxoria.App.sln
      Framework_Version: net9.0-windows10.0.26100.0

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: 'true'

      # Set up the .NET SDK (version 9.x)
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'
      
      # Set up Python 3.12
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Set up MSBuild for Windows build environment
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2
            
      # Build the main Luxoria.App solution
      - name: Build Luxoria.App
        run: |
          if ("${{ matrix.platform }}" -eq "win-x86") {
            $platformTarget = "x86"
          } elseif ("${{ matrix.platform }}" -eq "win-x64") {
            $platformTarget = "x64"
          } elseif ("${{ matrix.platform }}" -eq "win-arm64") {
            $platformTarget = "ARM64"
          } else {
            throw "Unknown platform: ${{ matrix.platform }}"
          }
          dotnet build Luxoria.App/Luxoria.App.sln --no-incremental -p:PackOnBuild=false -maxcpucount:1 -c ${{ matrix.configuration }} -r ${{ matrix.platform }} -p:PlatformTarget=$platformTarget
        shell: pwsh

      # Setup Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1

      # Install Poetry project dependencies
      - name: Install Marketplace Manager Dependencies
        run: C:\Users\runneradmin\.local\bin\poetry install
        working-directory: ./.tools/luxmktplacemgr

      # Run build modules
      - name: Build modules
        run: C:\Users\runneradmin\.local\bin\poetry run build ${{ matrix.platform }} ../../Modules
        working-directory: ./.tools/luxmktplacemgr
      
      # Archive builds
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Modules-${{ matrix.platform }}
          path: ./.tools/luxmktplacemgr/out
