name: Artifacts to Release

on:
  push:
    branches:
      - v*

jobs:
  exec-mods-build:
    uses: ./.github/workflows/build-modules.yml

  upload-artifacts-to-release:
    needs: [exec-mods-build]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: List downloaded artifacts
        run: ls ./artifacts

      - name: Create ZIP files for each artifact
        run: |
          for dir in ./artifacts/*; do
            if [ -d "$dir" ]; then
              zip -r "${dir}.zip" "$dir"
            fi
          done

      - uses: actions/checkout@v3
      - name: Create Tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "LuxoriaAgent"
          git tag -a "v${{ github.ref }}" -m "Luxoria Release v${{ github.ref }}"
          git push origin "v${{ github.ref }}"

      - name: Upload all artifacts to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref }}
          files: ./artifacts/*.zip

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
